/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_observateur (void);
GtkWidget* create_formulaire_OBSERVATEUR (void);
GtkWidget* create_utilisateurs (void);
GtkWidget* create_FORMULAIRE_UTILISATEURS_AJOUTER (void);
GtkWidget* create_LISTE_ELECTORALE (void);
GtkWidget* create_ELECTION (void);
GtkWidget* create_FORMULAIRE_ELECTION_AJOUTER (void);
GtkWidget* create_BUREAU_DE_VOTE (void);
GtkWidget* create_FORMULAIRE_BV_AJOUTER (void);
GtkWidget* create_RECLAMATION (void);
GtkWidget* create_SUPPRIMER_OBSERVATEUR (void);
GtkWidget* create_MODIFIER_AJOUTER_OBSERVATEUR (void);
GtkWidget* create_SUPPRIMER_UTLISATEUR (void);
GtkWidget* create_MODIFIER_UTILISATEUR (void);
GtkWidget* create_MODOFOER_TETE_DE_LA_LISTE_ELECTORALE (void);
GtkWidget* create_SUPPRIMER_BUREAU_DE_VOTE (void);
GtkWidget* create_MODIFIER_BV (void);
GtkWidget* create_MODIFIER__ELECTION (void);
GtkWidget* create_SUPPRIMER_ELECTION (void);
GtkWidget* create_FORMULAIRE_AJOUT_MUNICIPALIT__ (void);
GtkWidget* create_MODIFIER_MUNICIPALIT__ (void);
GtkWidget* create_formulaire_d_un_condidat (void);
GtkWidget* create_fontselectiondialog1 (void);
GtkWidget* create_modifier_un_condidat (void);
GtkWidget* create_CHERCHER_UN_CONDIDAT (void);
GtkWidget* create_ajouter_une_liste_electorale (void);
