/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *connexion;
  GtkWidget *observateur;
  GtkWidget *formulaire_OBSERVATEUR;
  GtkWidget *utilisateurs;
  GtkWidget *FORMULAIRE_UTILISATEURS_AJOUTER;
  GtkWidget *LISTE_ELECTORALE;
  GtkWidget *ELECTION;
  GtkWidget *FORMULAIRE_ELECTION_AJOUTER;
  GtkWidget *BUREAU_DE_VOTE;
  GtkWidget *FORMULAIRE_BV_AJOUTER;
  GtkWidget *RECLAMATION;
  GtkWidget *SUPPRIMER_OBSERVATEUR;
  GtkWidget *MODIFIER_AJOUTER_OBSERVATEUR;
  GtkWidget *SUPPRIMER_UTLISATEUR;
  GtkWidget *MODIFIER_UTILISATEUR;
  GtkWidget *MODOFOER_TETE_DE_LA_LISTE_ELECTORALE;
  GtkWidget *SUPPRIMER_BUREAU_DE_VOTE;
  GtkWidget *MODIFIER_BV;
  GtkWidget *MODIFIER__ELECTION;
  GtkWidget *SUPPRIMER_ELECTION;
  GtkWidget *FORMULAIRE_AJOUT_MUNICIPALIT__;
  GtkWidget *MODIFIER_MUNICIPALIT__;
  GtkWidget *formulaire_d_un_condidat;
  GtkWidget *fontselectiondialog1;
  GtkWidget *modifier_un_condidat;
  GtkWidget *CHERCHER_UN_CONDIDAT;
  GtkWidget *ajouter_une_liste_electorale;
  GtkWidget *treeview,*treeview1;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  LISTE_ELECTORALE=create_LISTE_ELECTORALE();
  gtk_widget_show(LISTE_ELECTORALE);
  treeview1=lookup_widget(LISTE_ELECTORALE,"treeviewlisteelectorale");
  afficherListeElectorale("listeelecorale.txt",treeview1);
  

  gtk_main ();
  return 0;
}

